---
title: "CodeBook"
author: "Shafeeq Ur Rahaman"
date: "4/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Following datasets were considered among all the available files in the present data analysis

### Original Datasets
1. `activity_labels.txt`: consists of all the labels (description) of activities
2. `features.txt`: list of all features
3. `subject_test.txt`: Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.
4. `subject_train.txt`: Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.
5. `X_train.txt`: training set for all the features
6. `X_test.txt`: test set for all the features
7. `y_train.txt`: training set for all the activity labels represented in numerical identifier of activity description
8. `y_test.txt`: test set for all the activity labels represented in numerical identifier of activity description

### Following is the description of the solution dataset that have been generated by cleaning

### Solution Datasets
#### 1. harTidy
a. `subject`: a numeric identifier for a subject who performed the activity
b. `activityNum`: a numerical identifier for the activity description
c. `activityLabel`: description of the activity performed
d. `variable`: variables that have been filtered according to the requirement of having mean and std
e. `measurement`: values of the variables that were filtered.

#### 2. harSummary
a. `subject`: a numeric identifier for a subject who performed the activity
b. `activityLabel`: description of the activity performed
c. `variable`: variables that have been filtered according to the requirement of having mean and std
d. `variable_average`: average of the grouped variables (grouped by subject and activityLabel)

## Transformations of data
1. Loaded `activity_labels.txt` and `features.text` by assigning column names
2. Loaded `subject_test.txt`, `X_test.txt`, `y_test.txt`, `subject_train.txt`, `X_train.txt`, `y_train.txt` by assigning appropriate self defined column names
3. Using `cbind` function combined all the files related to train and test into `train_all` and `test_all` respectively
4. Merged the train and test data together using `rbind` function into `harFull` dataset, which meets the requirement of combining all the required files
5. Using `Select` function extract only the measurements on the mean and standard deviation for each measurement and store them in a `harMini` by arranging (descending order) them using `arrange` function
6. Using `Merge` function merged `activity` dataset with `harMini` in order to add activity description to the activityNum present in the `harMini` dataset and saved the merged dataset as new `harMerge` dataset
7. Reorganized the columns in the dataset using `Select` function and converted the `activityNum` and `subject` columns to factors so as to tidy the dataset using `gather` function.
8. Applied `gather` function to form key value pairs, as the data was spread apart in columns and could be tidied by gathering them in rows under one column `variable` and with the respective values in the `measurement` column. Saving the result to the `harTidy` dataset
9. Independent tidy data set with the average of each variable for each activity and each subject by grouping the `harTidy` dataset based on `subject, activityLabel, variable` and summarizing using the `summarize` function to calculate the average and save in the `harSummary` dataset
10. Write the datasets into files using `write.table` function from `harTidy` and `harSummary` datasets.
